=== qiaozhou/usbdm-applications/XML_Files/Device_data/usbdmDeviceSchema.dtd
<!-- Root element -->
<!ELEMENT root (description,sharedInformation?,deviceList)>
     <!ATTLIST root version CDATA #REQUIRED>
  <!-- General Description element. -->
<!ELEMENT description (#PCDATA)>
  <!-- List of devices -->
<!ELEMENT deviceList (device*)>
  <!-- Device characteristics -->
<!ELEMENT device ((sdid*|
                   (clock?,
                    (memory|memoryRef)+,
                    (soptAddress|copctlAddress)?,
                    sdidAddress?,
                    sdidMask?,
                    sdid+,
                    flashScripts?,
                    (tclScript|tclScriptRef)?,
                    (flashProgram|flashProgramRef)?,
                    flashProgramData?,
                    (flexNVMInfo|flexNVMInfoRef)?)
                   ),
                  note*)>
     <!ATTLIST device name ID #REQUIRED>
     <!ATTLIST device alias IDREF #IMPLIED>
     <!ATTLIST device family (RS08|HCS08|HCS08Plus|HCS12|CFV1|CFV1Plus|CFVx|ARM|DSC) #IMPLIED>
     <!ATTLIST device isDefault (true) #IMPLIED>
     <!ATTLIST device speed CDATA #IMPLIED>
     <!ATTLIST device subfamily CDATA #IMPLIED>
     <!ATTLIST device hidden (true) #IMPLIED>
  <!-- Type of clock & characteristics -->
<!ELEMENT clock EMPTY>
     <!ATTLIST clock type (External|S08ICGV1|S08ICGV2|S08ICGV3|S08ICGV4|S08ICSV1|S08ICSV2|S08ICSV2x512|S08ICSV3|S08ICSV4|RS08ICSOSCV1|RS08ICSV1|S08MCGV1|S08MCGV2|S08MCGV3) "External">
     <!ATTLIST clock registerAddress CDATA "0">
  <!-- List of memory regions in device -->
<!ELEMENT memory (flashProgramRef?,
     (securityInfo|securityInfoRef)?,
     (securityInfo|securityInfoRef)?,
     (flexNVMInfo|flexNVMInfoRef)?,
     description?,
     (memoryRange+))>
     <!ATTLIST memory id               ID #IMPLIED>
     <!ATTLIST memory type             (ram|flash|pFlash|dFlash|eeprom|flexNVM|flexRAM|io|pRAM|pROM|xRAM|xROM) #REQUIRED>
     <!ATTLIST memory subType          CDATA "1">
     <!ATTLIST memory pageAddress      CDATA "0">
     <!ATTLIST memory registerAddress  CDATA "0">
     <!ATTLIST memory securityAddress  CDATA "0">
     <!ATTLIST memory alignment        CDATA #IMPLIED >
     <!ATTLIST memory sectorSize       CDATA #IMPLIED >
	  <!ATTLIST memory addressMode      (linear|paged) #IMPLIED>
  <!-- SOPT(1) register address -->
<!ELEMENT memoryRef EMPTY>
     <!ATTLIST memoryRef ref IDREF #REQUIRED>
<!ELEMENT securityInfo (#PCDATA)>
     <!ATTLIST securityInfo id         ID #IMPLIED>
     <!ATTLIST securityInfo size    CDATA #REQUIRED>
     <!ATTLIST securityInfo type (on|off) #REQUIRED>
<!ELEMENT securityInfoRef EMPTY>
     <!ATTLIST securityInfoRef ref IDREF #REQUIRED>
<!ELEMENT soptAddress EMPTY>
     <!ATTLIST soptAddress value CDATA #REQUIRED>
  <!-- SDID address -->
<!ELEMENT sdidAddress EMPTY>
     <!ATTLIST sdidAddress value CDATA #REQUIRED>
  <!--SDID mask for device significant bits -->
<!ELEMENT sdidMask EMPTY>
     <!ATTLIST sdidMask value CDATA #REQUIRED>
  <!-- Device SDID used to identify device -->
<!ELEMENT sdid EMPTY>
     <!ATTLIST sdid value CDATA #REQUIRED>
  <!--NVOPT memory address-->
<!ELEMENT nvoptAddress EMPTY>
     <!ATTLIST nvoptAddress value CDATA #REQUIRED>
  <!-- NVSEC memory address -->
<!ELEMENT nvsecAddress EMPTY>
     <!ATTLIST nvsecAddress value CDATA #REQUIRED>
  <!--COPTCTL register address-->
<!ELEMENT copctlAddress EMPTY>
     <!ATTLIST copctlAddress value CDATA #REQUIRED>
  <!--FSEC address-->
<!--!ELEMENT fsecAddress EMPTY-->
     <!--!ATTLIST fsecAddress value CDATA #REQUIRED-->
  <!-- FOPT address -->
<!--!ELEMENT foptAddress EMPTY-->
     <!--!ATTLIST foptAddress value CDATA #REQUIRED-->
  <!--Flash utility functions-->
<!ELEMENT flashScripts (tclScriptRef|tclScript)*>
  <!--Specifies a memory range-->
<!ELEMENT memoryRange (#PCDATA)>
     <!-- Various combinations may be used. Addresses are inclusive
     start  + end
     start  + size
     middle + size
     end    + size
     -->
     <!ATTLIST memoryRange start  CDATA #IMPLIED>
     <!ATTLIST memoryRange middle CDATA #IMPLIED>
     <!ATTLIST memoryRange end    CDATA #IMPLIED>
     <!ATTLIST memoryRange size   CDATA #IMPLIED>
     <!-- Various combinations may be used. pageStart,pageEnd are inclusive
     pageStart  + pageEnd
     pageStart  + pages
     pageEnd    + pages
     pageReset specifies the reset page number
     pageNo    specifies the page number for a single page
     -->
     <!ATTLIST memoryRange pageNo    CDATA #IMPLIED>
     <!ATTLIST memoryRange pageStart CDATA #IMPLIED>
     <!ATTLIST memoryRange pageEnd   CDATA #IMPLIED>
     <!ATTLIST memoryRange pages     CDATA #IMPLIED>
     <!ATTLIST memoryRange pageReset CDATA #IMPLIED>
  <!-- Note on device entry -->
<!ELEMENT note (#PCDATA)>
  <!-- Information shared between devices -->
<!ELEMENT sharedInformation (memory|tclScript|flashProgram|securityInfo|flexNVMInfo)*>
  <!--TCL Script-->
<!ELEMENT tclScript (#PCDATA)>
     <!ATTLIST tclScript id ID #IMPLIED>
  <!--Reference to TCL Script-->
<!ELEMENT tclScriptRef EMPTY>
     <!ATTLIST tclScriptRef ref IDREF #REQUIRED>
  <!--Flash program-->
<!ELEMENT flashProgram (#PCDATA)>
     <!ATTLIST flashProgram id ID #REQUIRED>
  <!--Reference to Flash program-->
<!ELEMENT flashProgramRef EMPTY>
     <!ATTLIST flashProgramRef ref IDREF #REQUIRED>
<!ELEMENT flashProgramData (#PCDATA)>
  <!--Partitioning of FlexNVM-->
<!ELEMENT flexNVMInfo (eeepromEntry+, partitionEntry+)>
     <!ATTLIST flexNVMInfo id ID #IMPLIED>
     <!ATTLIST flexNVMInfo backingRatio CDATA "16">
<!ELEMENT eeepromEntry EMPTY>
     <!ATTLIST eeepromEntry description CDATA "">
     <!ATTLIST eeepromEntry eeeSize     CDATA "0x00">
     <!ATTLIST eeepromEntry value       CDATA "0x00">
<!ELEMENT partitionEntry EMPTY>
     <!ATTLIST partitionEntry description   CDATA "">
     <!ATTLIST partitionEntry eeSize        CDATA "0x00">
     <!ATTLIST partitionEntry value         CDATA "0x00">
<!ELEMENT flexNVMInfoRef EMPTY>
     <!ATTLIST flexNVMInfoRef ref IDREF #REQUIRED>
   <!-- Example device entry
      <device family="RS08" name="MC9RS08KA1">
         <clock registerAddress="0x0014" type="RS08ICSV1" />
         <memory type="ram">
            <memoryRange end="0x004F" start="0x0020" />
         </memory>
         <memory registerAddress="0x210" type="flash">
            <memoryRange end="0x3FFF" start="0x3C00" />
         </memory>
         <soptAddress value="0x201" />
         <sdidAddress value="0x206" />
         <sdid value="0x800" />
         <note>Untested</note>
      </device>
      -->

=== qiaozhou/usbdm-applications/XML_Files/Device_data/cfvx_devices.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE DeviceList SYSTEM "usbdmDeviceSchema.dtd"
[
<!ENTITY CFV2-default-flashProgram      SYSTEM "CFVx/ColdfireV2-default-flash-program.elf.S19">
<!ENTITY CFV2-default-flashScripts      SYSTEM "CFVx/ColdfireV2-default-flash-scripts.tcl">
<!ENTITY Custom-Devices                 SYSTEM "Custom/custom-cfvx.xml">
]>
<root version="4.9.5">
   <description>Coldfire V2,3,4 device characteristics v4.7.0 10/8/2011</description>
   <sharedInformation>
      <flashProgram id="default-CFV2-FlashProgram">
         &CFV2-default-flashProgram;
      </flashProgram>
      <tclScript id="default-CFV2-Scripts">
         &CFV2-default-flashScripts;
      </tclScript>
      <!-- CFV2 Unsecured value = backdoor[8],CFMPROT[4],CFMSACC[4],CFMDACC[4],CFMSEC[4] -->
      <securityInfo size="24" type="off" id="CFV2-default-security-off">
         0000000000000000 00000000 00000000 00000000 00000000
      </securityInfo>
      <!-- CFV2 Secured value = backdoor[8],CFMPROT[4],CFMSACC[4],CFMDACC[4],CFMSEC[4] -->
      <securityInfo size="24" type="on" id="CFV2-default-security-on">
         FFFFFFFFFFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF C0004AC8
      </securityInfo>
      <memory id="coldfire4K_Ram" type="ram">
         <memoryRange start="0x20000000" size="4K" />
      </memory>
      <memory id="coldfire8K_Ram" type="ram">
         <memoryRange start="0x20000000" size="4K" />
      </memory>
      <memory id="coldfire16K_Ram" type="ram">
         <memoryRange start="0x20000000" size="16K" />
      </memory>
      <memory id="coldfire32K_Ram" type="ram">
         <memoryRange start="0x20000000" size="32K" />
      </memory>
      <memory id="coldfire64K_Ram" type="ram">
         <memoryRange start="0x20000000" size="64K" />
      </memory>
      <memory id="coldfire64K_Flash" type="flash" registerAddress="0x401D0000" securityAddress="0x0400" alignment="4"
         sectorSize="2048">
         <flashProgramRef ref="default-CFV2-FlashProgram" />
         <securityInfoRef ref="CFV2-default-security-off" />
         <securityInfoRef ref="CFV2-default-security-on" />
         <memoryRange start="0x000000" size="64K" />
      </memory>
      <memory id="coldfire128K_Flash" type="flash" registerAddress="0x401D0000" securityAddress="0x0400" alignment="4"
         sectorSize="2048">
         <flashProgramRef ref="default-CFV2-FlashProgram" />
         <securityInfoRef ref="CFV2-default-security-off" />
         <securityInfoRef ref="CFV2-default-security-on" />
         <memoryRange start="0x000000" size="128K" />
      </memory>
      <memory id="coldfire256K_Flash" type="flash" registerAddress="0x401D0000" securityAddress="0x0400" alignment="4"
         sectorSize="2048">
         <flashProgramRef ref="default-CFV2-FlashProgram" />
         <securityInfoRef ref="CFV2-default-security-off" />
         <securityInfoRef ref="CFV2-default-security-on" />
         <memoryRange start="0x000000" size="256K" />
      </memory>
      <memory id="coldfire512K_Flash" type="flash" registerAddress="0x401D0000" securityAddress="0x0400" alignment="4"
         sectorSize="2048">
         <flashProgramRef ref="default-CFV2-FlashProgram" />
         <securityInfoRef ref="CFV2-default-security-off" />
         <securityInfoRef ref="CFV2-default-security-on" />
         <memoryRange start="0x000000" size="512K" />
      </memory>
   </sharedInformation>
   <deviceList>
      <device family="CFVx" name="_Default" isDefault="true">
         <clock type="External" registerAddress="0" />
         <memory type="ram">
            <memoryRange start="0x20000000" size="4K" />
         </memory>
         <memory type="flash" registerAddress="0x401D0000" securityAddress="0x0400" sectorSize="2048" alignment="4">
            <securityInfoRef ref="CFV2-default-security-off" />
            <securityInfoRef ref="CFV2-default-security-on" />
            <memoryRange start="0x000000" size="512K" />
         </memory>
         <sdidAddress value="0x4011000A" />
         <sdidMask value="0xFFC0" />
         <sdid value="0x0000" />
         <tclScriptRef ref="default-CFV2-Scripts" />
         <flashProgramRef ref="default-CFV2-FlashProgram" />
         <note>Default CFV1 Device</note>
      </device>
      &Custom-Devices;
      <device family="CFVx" name="MCF52221">
         <clock type="External" registerAddress="0" />
         <memoryRef ref="coldfire16K_Ram" />
         <memoryRef ref="coldfire128K_Flash" />
         <sdid value="0x1400" />
      </device>
      <device family="CFVx" name="MCF52223">
         <clock type="External" registerAddress="0" />
         <memoryRef ref="coldfire16K_Ram" />
         <memoryRef ref="coldfire128K_Flash" />
         <sdid value="0x14C0" />
      </device>
      <device family="CFVx" name="MCF52230">
         <clock type="External" registerAddress="0" />
         <memoryRef ref="coldfire32K_Ram" />
         <memoryRef ref="coldfire128K_Flash" />
         <sdid value="0x1200" />
      </device>
      <device family="CFVx" name="MCF52231">
         <clock type="External" registerAddress="0" />
         <memoryRef ref="coldfire32K_Ram" />
         <memoryRef ref="coldfire128K_Flash" />
         <sdid value="0x1240" />
      </device>
      <device family="CFVx" name="MCF52232">
         <clock type="External" registerAddress="0" />
         <memoryRef ref="coldfire32K_Ram" />
         <memoryRef ref="coldfire128K_Flash" />
         <sdid value="0x0000" />
      </device>
      <device family="CFVx" name="MCF52233">
         <clock type="External" registerAddress="0" />
         <memoryRef ref="coldfire32K_Ram" />
         <memoryRef ref="coldfire256K_Flash" />
         <sdid value="0x1280" />
      </device>
      <device family="CFVx" name="MCF52234">
         <clock type="External" registerAddress="0" />
         <memoryRef ref="coldfire32K_Ram" />
         <memoryRef ref="coldfire256K_Flash" />
         <sdid value="0x12C0" />
      </device>
      <device family="CFVx" name="MCF52235">
         <clock type="External" registerAddress="0" />
         <memoryRef ref="coldfire32K_Ram" />
         <memoryRef ref="coldfire256K_Flash" />
         <sdid value="0x1300" />
      </device>
      <device family="CFVx" name="MCF52236">
         <clock type="External" registerAddress="0" />
         <memoryRef ref="coldfire32K_Ram" />
         <memoryRef ref="coldfire256K_Flash" />
         <sdid value="0x1280" />
      </device>
      <device family="CFVx" name="MCF52210">
         <clock type="External" registerAddress="0" />
         <memoryRef ref="coldfire16K_Ram" />
         <memoryRef ref="coldfire64K_Flash" />
         <sdid value="0x0" />
      </device>
      <device family="CFVx" name="MCF52211">
         <clock type="External" registerAddress="0" />
         <memoryRef ref="coldfire16K_Ram" />
         <memoryRef ref="coldfire128K_Flash" />
         <sdid value="0x0" />
      </device>
      <device family="CFVx" name="MCF52212">
         <clock type="External" registerAddress="0" />
         <memoryRef ref="coldfire8K_Ram" />
         <memoryRef ref="coldfire64K_Flash" />
         <sdid value="0x0" />
      </device>
      <device family="CFVx" name="MCF52213">
         <clock type="External" registerAddress="0" />
         <memoryRef ref="coldfire8K_Ram" />
         <memoryRef ref="coldfire128K_Flash" />
         <sdid value="0x1580" />
      </device>
      <!--
         =======================================================================
      -->
      <device family="CFVx" name="MCF52259">
         <clock type="External" registerAddress="0" />
         <memoryRef ref="coldfire64K_Ram" />
         <memory type="io">
            <memoryRange size="1024M" start="0x40000000" />
         </memory>
         <memoryRef ref="coldfire512K_Flash" />
         <sdid value="0x2481" />
      </device>
   </deviceList>
</root>

=== qiaozhou/usbdm-applications/XML_Files/Device_data/rs08_devices.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE DeviceList SYSTEM "usbdmDeviceSchema.dtd"
[
<!ENTITY RS08-default-flashScripts      SYSTEM "RS08/RS08-default-flash-scripts.tcl">
]>
<root version="4.8.0">
   <description>RS08 Device characteristics v4.8.0 5/12/2011</description>
   <sharedInformation>
      <tclScript id="RS08-default-Scripts">
         &RS08-default-flashScripts;
      </tclScript>
      <!-- RS08 Unsecured value = NVOPT -->
      <securityInfo size="1" type="off" id="RS08-default-security-off">
         FF
      </securityInfo>
      <!-- RS08 Secured value = NVOPT -->
      <securityInfo size="1" type="on" id="RS08-default-security-on">
         FE
      </securityInfo>
   </sharedInformation>
   <deviceList>
      <device family="RS08" name="_Default" isDefault="true" >
         <clock type="External" />
         <memory type="ram">
            <memoryRange end="0x004F" start="0x0020" />
         </memory>
         <memory registerAddress="0x210" type="flash" securityAddress="0x3FFC">
            <securityInfoRef ref="RS08-default-security-off" />
            <securityInfoRef ref="RS08-default-security-on" />
            <memoryRange end="0x3FFF" start="0x3C00" />
         </memory>
         <sdidMask value="0xFFF" />
         <sdid value="0x0" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
         <note>Default RS08 Device</note>
      </device>
      <device family="RS08" name="MC9RS08KA1">
         <clock registerAddress="0x0014" type="RS08ICSV1" />
         <memory type="ram">
            <memoryRange end="0x004F" start="0x0020" />
         </memory>
         <memory registerAddress="0x210" type="flash" securityAddress="0x3FFC">
            <securityInfoRef ref="RS08-default-security-off" />
            <securityInfoRef ref="RS08-default-security-on" />
            <memoryRange end="0x3FFF" start="0x3C00" />
         </memory>
         <soptAddress value="0x201" />
         <sdidAddress value="0x206" />
         <sdid value="0x800" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
      </device>
      <device family="RS08" name="MC9RS08KA2">
         <clock registerAddress="0x0014" type="RS08ICSV1" />
         <memory type="ram">
            <memoryRange end="0x004F" start="0x0020" />
         </memory>
         <memory registerAddress="0x210" type="flash" securityAddress="0x3FFC">
            <securityInfoRef ref="RS08-default-security-off" />
            <securityInfoRef ref="RS08-default-security-on" />
            <memoryRange end="0x3FFF" start="0x3800" />
         </memory>
         <soptAddress value="0x201" />
         <sdidAddress value="0x206" />
         <sdid value="0x800" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
         <note>Untested</note>
      </device>
      <device family="RS08" name="MC9RS08KA4">
         <clock registerAddress="0x023C" type="RS08ICSOSCV1" />
         <memory type="ram">
            <memoryRange end="0x009F" start="0x0030" />
         </memory>
         <memory registerAddress="0x210" type="flash" securityAddress="0x3FFC">
            <securityInfoRef ref="RS08-default-security-off" />
            <securityInfoRef ref="RS08-default-security-on" />
            <memoryRange end="0x3FFF" start="0x3000" />
         </memory>
         <soptAddress value="0x201" />
         <sdidAddress value="0x206" />
         <sdid value="0x803" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
         <note>Untested</note>
      </device>
      <device family="RS08" name="MC9RS08KA8">
         <clock registerAddress="0x023C" type="RS08ICSOSCV1" />
         <memory type="ram">
            <memoryRange end="0x00BF" start="0x0030" />
         </memory>
         <memory registerAddress="0x210" type="flash" securityAddress="0x3FFC">
            <securityInfoRef ref="RS08-default-security-off" />
            <securityInfoRef ref="RS08-default-security-on" />
            <memoryRange end="0x3FFF" start="0x2000" />
         </memory>
         <soptAddress value="0x201" />
         <sdidAddress value="0x206" />
         <sdid value="0x803" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
      </device>
      <device family="RS08" name="MC9RS08KB2">
         <clock registerAddress="0x0238" type="S08ICSV1" />
         <memory type="ram">
            <memoryRange end="0x00BF" start="0x0050" />
         </memory>
         <memory registerAddress="0x208" type="flash" securityAddress="0x3FFC">
            <securityInfoRef ref="RS08-default-security-off" />
            <securityInfoRef ref="RS08-default-security-on" />
            <memoryRange end="0x3FFF" start="0x3800" />
         </memory>
         <soptAddress value="0x211" />
         <sdidAddress value="0x216" />
         <sdid value="0x806" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
         <note>Untested</note>
      </device>
      <device family="RS08" name="MC9RS08KB4">
         <clock registerAddress="0x0238" type="S08ICSV1" />
         <memory type="ram">
            <memoryRange end="0x00BF" start="0x0050" />
         </memory>
         <memory registerAddress="0x208" type="flash" securityAddress="0x3FFC">
            <securityInfoRef ref="RS08-default-security-off" />
            <securityInfoRef ref="RS08-default-security-on" />
            <memoryRange end="0x3FFF" start="0x3000" />
         </memory>
         <soptAddress value="0x211" />
         <sdidAddress value="0x216" />
         <sdid value="0x806" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
         <note>Untested</note>
      </device>
      <device family="RS08" name="MC9RS08KB8">
         <clock registerAddress="0x0238" type="S08ICSV1" />
         <memory type="ram">
            <memoryRange end="0x00BF" start="0x0050" />
         </memory>
         <memory registerAddress="0x208" type="flash" securityAddress="0x3FFC">
            <securityInfoRef ref="RS08-default-security-off" />
            <securityInfoRef ref="RS08-default-security-on" />
            <memoryRange end="0x3FFF" start="0x2000" />
         </memory>
         <soptAddress value="0x211" />
         <sdidAddress value="0x216" />
         <sdid value="0x806" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
         <note>Untested</note>
      </device>
      <device family="RS08" name="MC9RS08KB12">
         <clock registerAddress="0x0238" type="S08ICSV1" />
         <memory type="ram">
            <memoryRange end="0x00BF" start="0x0050" />
         </memory>
         <memory registerAddress="0x208" type="flash" securityAddress="0x3FFC">
            <securityInfoRef ref="RS08-default-security-off" />
            <securityInfoRef ref="RS08-default-security-on" />
            <memoryRange end="0x3FFF" start="0x1000" />
         </memory>
         <soptAddress value="0x211" />
         <sdidAddress value="0x216" />
         <sdid value="0x806" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
         <note>Untested</note>
      </device>
      <device family="RS08" name="MC9RS08LA8">
         <clock registerAddress="0x022C" type="RS08ICSV1" />
         <memory type="ram">
            <memoryRange end="0x00BF" start="0x0050" />
         </memory>
         <memory registerAddress="0x250" type="flash" securityAddress="0x3FFC">
            <securityInfoRef ref="RS08-default-security-off" />
            <securityInfoRef ref="RS08-default-security-on" />
            <memoryRange end="0x3FFF" start="0x2000" />
         </memory>
         <soptAddress value="0x019" />
         <sdidAddress value="0x216" />
         <sdid value="0x804" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
      </device>
      <device family="RS08" name="MC9RS08LE4">
         <clock registerAddress="0x022C" type="S08ICSV2x512" />
         <memory type="ram">
            <memoryRange end="0x00BF" start="0x0050" />
         </memory>
         <memory registerAddress="0x23C" type="flash" securityAddress="0x3FFC">
            <securityInfoRef ref="RS08-default-security-off" />
            <securityInfoRef ref="RS08-default-security-on" />
            <memoryRange end="0x3FFF" start="0x3000" />
         </memory>
         <soptAddress value="0x019" />
         <sdidAddress value="0x21A" />
         <sdid value="0x805" />
         <flashScripts>
            <tclScriptRef ref="RS08-default-Scripts" />
         </flashScripts>
      </device>
   </deviceList>
</root>
